export const ALL_PERMISSIONS = [
  { id: "dashboard.view", label: "View Dashboard", module: "Dashboard" },
  { id: "vacancies.view", label: "View Vacancies", module: "Vacancies" },
  { id: "vacancies.create", label: "Create Vacancies", module: "Vacancies" },
  { id: "vacancies.edit", label: "Edit Vacancies", module: "Vacancies" },
  { id: "vacancies.delete", label: "Delete Vacancies", module: "Vacancies" },
  { id: "applications.view", label: "View Applications", module: "Applications" },
  { id: "applications.manage", label: "Manage Applications", module: "Applications" },
  { id: "candidates.view", label: "View Candidates", module: "Candidates" },
  { id: "candidates.create", label: "Create Candidates", module: "Candidates" },
  { id: "candidates.edit", label: "Edit Candidates", module: "Candidates" },
  { id: "candidates.delete", label: "Delete Candidates", module: "Candidates" },
  { id: "candidates.score", label: "Score Candidates", module: "Candidates" },
  { id: "candidates.export", label: "Export Candidates", module: "Candidates" },
  { id: "interviews.view", label: "View Interviews", module: "Interviews" },
  { id: "interviews.schedule", label: "Schedule Interviews", module: "Interviews" },
  { id: "interviews.edit", label: "Edit Interviews", module: "Interviews" },
  { id: "interviews.cancel", label: "Cancel Interviews", module: "Interviews" },
  { id: "whatsapp.view", label: "View WhatsApp", module: "WhatsApp" },
  { id: "whatsapp.send", label: "Send WhatsApp", module: "WhatsApp" },
  { id: "email.view", label: "View Email", module: "Email" },
  { id: "email.send", label: "Send Email", module: "Email" },
  { id: "departments.view", label: "View Departments", module: "Departments" },
  { id: "departments.manage", label: "Manage Departments", module: "Departments" },
  { id: "branches.view", label: "View Branches", module: "Branches" },
  { id: "branches.manage", label: "Manage Branches", module: "Branches" },
  { id: "reports.view", label: "View Reports", module: "Reports" },
  { id: "reports.export", label: "Export Reports", module: "Reports" },
  { id: "users.view", label: "View Users", module: "Users" },
  { id: "users.create", label: "Create Users", module: "Users" },
  { id: "users.edit", label: "Edit Users", module: "Users" },
  { id: "users.delete", label: "Delete Users", module: "Users" },
  { id: "users.reset_password", label: "Reset Passwords", module: "Users" },
  { id: "templates.view", label: "View Templates", module: "Templates" },
  { id: "templates.manage", label: "Manage Templates", module: "Templates" },
  { id: "settings.view", label: "View Settings", module: "Settings" },
  { id: "settings.edit", label: "Edit Settings", module: "Settings" },
  { id: "settings.roles", label: "Manage Roles & Permissions", module: "Settings" },
  { id: "audit_logs.view", label: "View Audit Logs", module: "Audit Logs" },
  { id: "tenants.view", label: "View Clients", module: "Clients" },
  { id: "tenants.manage", label: "Manage Clients", module: "Clients" },
] as const;

export type PermissionId = (typeof ALL_PERMISSIONS)[number]["id"];

export const PERMISSION_MODULES = [...new Set(ALL_PERMISSIONS.map((p) => p.module))];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  super_admin: ALL_PERMISSIONS.map((p) => p.id),
  tenant_admin: [
    "dashboard.view", "vacancies.view", "vacancies.create", "vacancies.edit",
    "applications.view", "applications.manage",
    "candidates.view", "candidates.create", "candidates.edit", "candidates.score", "candidates.export",
    "interviews.view", "interviews.schedule", "interviews.edit", "interviews.cancel",
    "whatsapp.view", "whatsapp.send", "email.view", "email.send",
    "departments.view", "departments.manage", "branches.view", "branches.manage",
    "reports.view", "reports.export",
    "users.view", "users.create", "users.edit", "users.delete", "users.reset_password",
    "templates.view", "templates.manage",
    "settings.view", "settings.edit", "settings.roles", "audit_logs.view",
  ],
  hr_manager: [
    "dashboard.view", "vacancies.view", "vacancies.create", "vacancies.edit",
    "applications.view", "applications.manage",
    "candidates.view", "candidates.create", "candidates.edit", "candidates.score", "candidates.export",
    "interviews.view", "interviews.schedule", "interviews.edit", "interviews.cancel",
    "whatsapp.view", "whatsapp.send", "email.view", "email.send",
    "departments.view", "branches.view",
    "reports.view", "reports.export",
    "users.view", "templates.view", "templates.manage",
    "settings.view", "audit_logs.view",
  ],
  hr_executive: [
    "dashboard.view", "vacancies.view",
    "applications.view", "applications.manage",
    "candidates.view", "candidates.create", "candidates.edit", "candidates.score",
    "interviews.view", "interviews.schedule", "interviews.edit",
    "whatsapp.view", "whatsapp.send", "email.view", "email.send",
    "departments.view", "branches.view",
    "reports.view",
    "templates.view",
    "settings.view",
  ],
  recruitment_manager: [
    "dashboard.view", "vacancies.view", "vacancies.create", "vacancies.edit",
    "applications.view", "applications.manage",
    "candidates.view", "candidates.create", "candidates.edit", "candidates.score", "candidates.export",
    "interviews.view", "interviews.schedule", "interviews.edit", "interviews.cancel",
    "email.view", "email.send",
    "departments.view", "branches.view",
    "reports.view", "reports.export",
    "templates.view",
    "settings.view",
  ],
  viewer: [
    "dashboard.view", "vacancies.view", "applications.view",
    "candidates.view", "interviews.view",
    "departments.view", "branches.view",
    "reports.view", "templates.view",
  ],
};
