import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import "dotenv/config";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const TENANT_ID = "cmrpd6mgi00001cfo6t4njhm1";
const TNAME = "Lords Health Care";

async function main() {
  console.log(`Seeding ${TENANT_ID} data for ${TNAME}...`);

  // Clean existing tenant-scoped data (order respects FK constraints)
  await prisma.interviewRecord.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.candidate.deleteMany({ where: { tenantId: TENANT_ID } });
  // cascade: candidate delete removes CandidateScore, Remark, Communication, StatusHistory
  await prisma.job.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.department.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.hospitalBranch.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.auditLog.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.notification.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.template.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.user.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.setting.deleteMany({ where: { tenantId: TENANT_ID } });
  await prisma.tenant.delete({ where: { id: TENANT_ID } }).catch(() => {});

  // Create tenant
  await prisma.tenant.create({
    data: {
      id: TENANT_ID,
      name: TNAME,
      slug: "lords-health-care",
      email: "info@lordshealthcare.org",
      phone: "+91 22 4567 8900",
      address: "456 Healthcare Avenue, Andheri East",
      city: "Mumbai",
      state: "Maharashtra",
      plan: "enterprise",
      isActive: true,
      maxUsers: 25,
      maxJobs: 100,
    },
  });
  console.log("Tenant created.");

  // 10 Users
  await Promise.all([
    prisma.user.create({ data: { id: "tu1", tenantId: TENANT_ID, name: "Soyeb Alam", email: "soyeb.alam@lordshealthcare.org", password: "123456", role: "tenant_admin", department: "Administration", phone: "+91 98765 43201" } }),
    prisma.user.create({ data: { id: "tu2", tenantId: TENANT_ID, name: "Dr. Fatima Sheikh", email: "fatima.sheikh@lordshealthcare.org", password: "123456", role: "hr_manager", department: "Human Resources", phone: "+91 98765 43202" } }),
    prisma.user.create({ data: { id: "tu3", tenantId: TENANT_ID, name: "Mr. Rohan Desai", email: "rohan.desai@lordshealthcare.org", password: "123456", role: "recruitment_manager", department: "Recruitment", phone: "+91 98765 43203" } }),
    prisma.user.create({ data: { id: "tu4", tenantId: TENANT_ID, name: "Ms. Priya Kapoor", email: "priya.kapoor@lordshealthcare.org", password: "123456", role: "hr_executive", department: "Human Resources", phone: "+91 98765 43204" } }),
    prisma.user.create({ data: { id: "tu5", tenantId: TENANT_ID, name: "Dr. Arjun Mehta", email: "arjun.mehta@lordshealthcare.org", password: "123456", role: "hr_manager", department: "Medical Affairs", phone: "+91 98765 43205" } }),
    prisma.user.create({ data: { id: "tu6", tenantId: TENANT_ID, name: "Ms. Neelam Joshi", email: "neelam.joshi@lordshealthcare.org", password: "123456", role: "hr_executive", department: "Nursing Admin", phone: "+91 98765 43206" } }),
    prisma.user.create({ data: { id: "tu7", tenantId: TENANT_ID, name: "Mr. Vicky Singh", email: "vicky.singh@lordshealthcare.org", password: "123456", role: "viewer", department: "Operations", phone: "+91 98765 43207" } }),
    prisma.user.create({ data: { id: "tu8", tenantId: TENANT_ID, name: "Dr. Shweta Patel", email: "shweta.patel@lordshealthcare.org", password: "123456", role: "hr_manager", department: "Emergency Services", phone: "+91 98765 43208" } }),
    prisma.user.create({ data: { id: "tu9", tenantId: TENANT_ID, name: "Mr. Imran Khan", email: "imran.khan@lordshealthcare.org", password: "123456", role: "recruitment_manager", department: "Recruitment", phone: "+91 98765 43209" } }),
    prisma.user.create({ data: { id: "tu10", tenantId: TENANT_ID, name: "Ms. Divya Nair", email: "divya.nair@lordshealthcare.org", password: "123456", role: "hr_executive", department: "Human Resources", phone: "+91 98765 43210" } }),
  ]);
  console.log("10 Users created.");

  // 10 Departments
  await Promise.all([
    prisma.department.create({ data: { id: "td1", tenantId: TENANT_ID, name: "Cardiology", code: "LHC-CARD", head: "Dr. Arjun Mehta", totalPositions: 15, openPositions: 4, color: "#EF4444" } }),
    prisma.department.create({ data: { id: "td2", tenantId: TENANT_ID, name: "Neurology", code: "LHC-NEUR", head: "Dr. Suresh Iyer", totalPositions: 10, openPositions: 3, color: "#3B82F6" } }),
    prisma.department.create({ data: { id: "td3", tenantId: TENANT_ID, name: "Orthopedics", code: "LHC-ORTH", head: "Dr. Vikram Joshi", totalPositions: 8, openPositions: 2, color: "#10B981" } }),
    prisma.department.create({ data: { id: "td4", tenantId: TENANT_ID, name: "Nursing", code: "LHC-NURS", head: "Ms. Neelam Joshi", totalPositions: 50, openPositions: 15, color: "#F59E0B" } }),
    prisma.department.create({ data: { id: "td5", tenantId: TENANT_ID, name: "Radiology & Imaging", code: "LHC-RAD", head: "Dr. Pooja Sharma", totalPositions: 8, openPositions: 2, color: "#8B5CF6" } }),
    prisma.department.create({ data: { id: "td6", tenantId: TENANT_ID, name: "Emergency Medicine", code: "LHC-EMER", head: "Dr. Shweta Patel", totalPositions: 25, openPositions: 6, color: "#EC4899" } }),
    prisma.department.create({ data: { id: "td7", tenantId: TENANT_ID, name: "Pharmacy", code: "LHC-PHAR", head: "Dr. Amit Shah", totalPositions: 12, openPositions: 4, color: "#06B6D4" } }),
    prisma.department.create({ data: { id: "td8", tenantId: TENANT_ID, name: "Pathology & Lab", code: "LHC-LAB", head: "Dr. Kavita Rao", totalPositions: 10, openPositions: 3, color: "#6366F1" } }),
    prisma.department.create({ data: { id: "td9", tenantId: TENANT_ID, name: "ICU / Critical Care", code: "LHC-ICU", head: "Dr. Rajesh Menon", totalPositions: 30, openPositions: 8, color: "#EF4444" } }),
    prisma.department.create({ data: { id: "td10", tenantId: TENANT_ID, name: "Pediatrics", code: "LHC-PED", head: "Dr. Ananya Verma", totalPositions: 12, openPositions: 5, color: "#14B8A6" } }),
  ]);
  console.log("10 Departments created.");

  // 10 Branches
  await Promise.all([
    prisma.hospitalBranch.create({ data: { id: "tb1", tenantId: TENANT_ID, name: "Lords Health Care - Andheri", code: "LHC-AND", address: "456 Healthcare Avenue, Andheri East", city: "Mumbai", state: "Maharashtra", phone: "+91 22 4567 8901", email: "andheri@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb2", tenantId: TENANT_ID, name: "Lords Health Care - Bandra", code: "LHC-BAN", address: "78 Sea Face Road, Bandra West", city: "Mumbai", state: "Maharashtra", phone: "+91 22 4567 8902", email: "bandra@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb3", tenantId: TENANT_ID, name: "Lords Health Care - Thane", code: "LHC-THN", address: "12 Lake Gardens, Thane West", city: "Thane", state: "Maharashtra", phone: "+91 22 4567 8903", email: "thane@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb4", tenantId: TENANT_ID, name: "Lords Health Care - Pune", code: "LHC-PUN", address: "90 Koregaon Park, Pune", city: "Pune", state: "Maharashtra", phone: "+91 20 4567 8904", email: "pune@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb5", tenantId: TENANT_ID, name: "Lords Health Care - Nagpur", code: "LHC-NAG", address: "45 Civil Lines, Nagpur", city: "Nagpur", state: "Maharashtra", phone: "+91 712 4567 8905", email: "nagpur@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb6", tenantId: TENANT_ID, name: "Lords Health Care - Nashik", code: "LHC-NAS", address: "23 College Road, Nashik", city: "Nashik", state: "Maharashtra", phone: "+91 253 4567 8906", email: "nashik@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb7", tenantId: TENANT_ID, name: "Lords Health Care - Aurangabad", code: "LHC-AUR", address: "67 Jalna Road, Aurangabad", city: "Aurangabad", state: "Maharashtra", phone: "+91 240 4567 8907", email: "aurangabad@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb8", tenantId: TENANT_ID, name: "Lords Health Care - Kolhapur", code: "LHC-KOL", address: "34 Station Road, Kolhapur", city: "Kolhapur", state: "Maharashtra", phone: "+91 231 4567 8908", email: "kolhapur@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb9", tenantId: TENANT_ID, name: "Lords Health Care - Solapur", code: "LHC-SOL", address: "89 Market Yard, Solapur", city: "Solapur", state: "Maharashtra", phone: "+91 217 4567 8909", email: "solapur@lordshealthcare.org" } }),
    prisma.hospitalBranch.create({ data: { id: "tb10", tenantId: TENANT_ID, name: "Lords Health Care - Navi Mumbai", code: "LHC-NVM", address: "56 Palm Beach Road, Vashi", city: "Navi Mumbai", state: "Maharashtra", phone: "+91 22 4567 8910", email: "navimumbai@lordshealthcare.org" } }),
  ]);
  console.log("10 Branches created.");

  // 10 Jobs
  await Promise.all([
    prisma.job.create({ data: { id: "tj1", tenantId: TENANT_ID, title: "Senior Cardiologist", departmentId: "td1", branchId: "tb1", location: "Mumbai", employmentType: "full_time", experienceRequired: "8-12 years", salaryMin: 300000, salaryMax: 500000, qualification: "DM Cardiology", skills: ["Echocardiography", "Angioplasty", "Cardiac CT"], vacancies: 2, description: "Lead our cardiology department at Andheri branch.", responsibilities: ["Cardiac procedures", "Mentor junior doctors", "OPD consultations"], benefits: ["Health Insurance", "CME Allowance", "Performance Bonus"], expiryDate: "2026-12-31", hiringManager: "Dr. Arjun Mehta", status: "open", isUrgent: true, applyLink: "/careers/lhc-senior-cardiologist" } }),
    prisma.job.create({ data: { id: "tj2", tenantId: TENANT_ID, title: "Staff Nurse - ICU", departmentId: "td9", branchId: "tb2", location: "Mumbai", employmentType: "full_time", experienceRequired: "2-5 years", salaryMin: 40000, salaryMax: 70000, qualification: "B.Sc Nursing / GNM", skills: ["Critical Care", "Ventilator Management", "Patient Monitoring"], vacancies: 6, description: "Join our ICU team at Bandra branch.", responsibilities: ["Monitor ICU patients", "Administer medications", "Coordinate with intensivists"], benefits: ["Health Insurance", "Night Shift Allowance", "Meals Provided"], expiryDate: "2026-11-30", hiringManager: "Ms. Neelam Joshi", status: "urgent", isUrgent: true, applyLink: "/careers/lhc-icu-nurse" } }),
    prisma.job.create({ data: { id: "tj3", tenantId: TENANT_ID, title: "Neurologist", departmentId: "td2", branchId: "tb4", location: "Pune", employmentType: "full_time", experienceRequired: "6-10 years", salaryMin: 250000, salaryMax: 450000, qualification: "DM Neurology", skills: ["Stroke Management", "EEG", "Neuroimaging"], vacancies: 1, description: "Join our neurology team at Pune branch.", responsibilities: ["Neurology OPD", "Stroke protocol", "Neuro interventions"], benefits: ["Health Insurance", "Research Grant", "Relocation Assistance"], expiryDate: "2026-10-31", hiringManager: "Dr. Fatima Sheikh", status: "open", isUrgent: false, applyLink: "/careers/lhc-neurologist" } }),
    prisma.job.create({ data: { id: "tj4", tenantId: TENANT_ID, title: "Orthopedic Surgeon", departmentId: "td3", branchId: "tb3", location: "Thane", employmentType: "full_time", experienceRequired: "8-15 years", salaryMin: 350000, salaryMax: 600000, qualification: "MS Orthopedics / DNB", skills: ["Joint Replacement", "Arthroscopy", "Trauma Surgery"], vacancies: 1, description: "Lead orthopedic services at Thane branch.", responsibilities: ["Joint replacement surgeries", "Arthroscopic procedures", "Fracture management"], benefits: ["Health Insurance", "Surgery Bonus", "OPD commission"], expiryDate: "2026-12-31", hiringManager: "Mr. Rohan Desai", status: "open", isUrgent: true, applyLink: "/careers/lhc-orthopedic-surgeon" } }),
    prisma.job.create({ data: { id: "tj5", tenantId: TENANT_ID, title: "Radiologist", departmentId: "td5", branchId: "tb1", location: "Mumbai", employmentType: "full_time", experienceRequired: "5-8 years", salaryMin: 200000, salaryMax: 350000, qualification: "MD Radiology", skills: ["MRI", "CT Scan", "Ultrasound", "Mammography"], vacancies: 2, description: "Radiologist for our advanced imaging center.", responsibilities: ["Interpret imaging", "Report findings", "Image-guided procedures"], benefits: ["Health Insurance", "CME Allowance", "Flexible Schedule"], expiryDate: "2026-09-30", hiringManager: "Dr. Pooja Sharma", status: "open", isUrgent: false, applyLink: "/careers/lhc-radiologist" } }),
    prisma.job.create({ data: { id: "tj6", tenantId: TENANT_ID, title: "Emergency Physician", departmentId: "td6", branchId: "tb5", location: "Nagpur", employmentType: "full_time", experienceRequired: "5-10 years", salaryMin: 180000, salaryMax: 320000, qualification: "MD Emergency Medicine / MEM", skills: ["Trauma Care", "ACLS", "ATLS", "Ultrasound"], vacancies: 3, description: "Join our emergency department at Nagpur.", responsibilities: ["Emergency care", "Trauma team lead", "Resuscitation"], benefits: ["Health Insurance", "Night Shift Allowance", "Loading"], expiryDate: "2026-08-31", hiringManager: "Dr. Shweta Patel", status: "urgent", isUrgent: true, applyLink: "/careers/lhc-emergency-physician" } }),
    prisma.job.create({ data: { id: "tj7", tenantId: TENANT_ID, title: "Clinical Pharmacist", departmentId: "td7", branchId: "tb6", location: "Nashik", employmentType: "full_time", experienceRequired: "3-6 years", salaryMin: 45000, salaryMax: 75000, qualification: "Pharm.D / M.Pharm", skills: ["Clinical Pharmacy", "Drug Interaction", "Inventory Management"], vacancies: 2, description: "Clinical pharmacist for our Nashik branch.", responsibilities: ["Medication review", "Patient counseling", "Inventory management"], benefits: ["Health Insurance", "Education Assistance"], expiryDate: "2026-10-15", hiringManager: "Dr. Amit Shah", status: "open", isUrgent: false, applyLink: "/careers/lhc-clinical-pharmacist" } }),
    prisma.job.create({ data: { id: "tj8", tenantId: TENANT_ID, title: "Lab Technician", departmentId: "td8", branchId: "tb7", location: "Aurangabad", employmentType: "full_time", experienceRequired: "1-3 years", salaryMin: 25000, salaryMax: 40000, qualification: "B.Sc MLT / DMLT", skills: ["Hematology", "Biochemistry", "Microbiology"], vacancies: 3, description: "Lab technician for pathology department.", responsibilities: ["Sample collection", "Lab testing", "Equipment maintenance"], benefits: ["Health Insurance", "Transport Allowance"], expiryDate: "2026-11-30", hiringManager: "Dr. Kavita Rao", status: "open", isUrgent: false, applyLink: "/careers/lhc-lab-technician" } }),
    prisma.job.create({ data: { id: "tj9", tenantId: TENANT_ID, title: "Pediatrician", departmentId: "td10", branchId: "tb8", location: "Kolhapur", employmentType: "full_time", experienceRequired: "4-8 years", salaryMin: 150000, salaryMax: 280000, qualification: "MD Pediatrics", skills: ["Neonatology", "Pediatric Care", "Vaccination"], vacancies: 2, description: "Pediatrician for our Kolhapur branch.", responsibilities: ["Pediatric OPD", "NICU care", "Wellness checkups"], benefits: ["Health Insurance", "CME Allowance", "Flexible Hours"], expiryDate: "2026-12-31", hiringManager: "Dr. Ananya Verma", status: "open", isUrgent: false, applyLink: "/careers/lhc-pediatrician" } }),
    prisma.job.create({ data: { id: "tj10", tenantId: TENANT_ID, title: "Hospital Administrator", departmentId: "td8", branchId: "tb10", location: "Navi Mumbai", employmentType: "full_time", experienceRequired: "8-12 years", salaryMin: 120000, salaryMax: 220000, qualification: "MHA / MBA Healthcare", skills: ["Operations", "Compliance", "Team Leadership", "Budgeting"], vacancies: 1, description: "Administer operations at our Navi Mumbai branch.", responsibilities: ["Daily operations", "Staff management", "Regulatory compliance"], benefits: ["Health Insurance", "Performance Bonus", "Vehicle Allowance"], expiryDate: "2026-09-30", hiringManager: "Soyeb Alam", status: "open", isUrgent: false, applyLink: "/careers/lhc-hospital-administrator" } }),
  ]);
  console.log("10 Jobs created.");

  // 10 Candidates with nested data
  await prisma.candidate.create({ data: { id: "tc1", tenantId: TENANT_ID, applicationNumber: "LHC-2026-001", fullName: "Dr. Aisha Khan", gender: "female", dob: "1985-03-15", email: "aisha.khan@email.com", mobile: "+91 98765 20001", whatsapp: "+91 98765 20001", whatsappVerified: true, emailVerified: true, address: "12 Colaba Causeway", city: "Mumbai", state: "Maharashtra", pin: "400005", qualification: "DM Cardiology", experience: "10 years", currentEmployer: "Jupiter Hospital", currentSalary: 280000, expectedSalary: 420000, noticePeriod: "60 days", languages: ["English", "Hindi", "Urdu"], skills: ["Echocardiography", "Angioplasty", "Cardiac CT"], jobId: "tj1", applicationDate: new Date("2026-07-01"), status: "shortlisted", assignedHRId: "tu2", tags: ["top_candidate", "senior"], score: { create: { communication: 9, technicalSkill: 9, experience: 9, qualification: 9, personality: 8, hospitalCultureFit: 8, computerKnowledge: 7, leadership: 8, confidence: 9, overall: 8.4 } }, remarks: { createMany: { data: [{ id: "tr1", userId: "tu2", type: "overall", content: "Excellent cardiologist with strong procedural experience.", isPinned: true, colorLabel: "green" }] } }, communications: { createMany: { data: [{ id: "tcm1", type: "whatsapp", direction: "outbound", content: "Dear Aisha, your application for Senior Cardiologist has been shortlisted.", status: "delivered", createdAt: new Date("2026-07-02T10:00:00Z") }] } }, statusHistory: { createMany: { data: [{ id: "tsh1", userId: "tu2", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-01T08:00:00Z") }, { id: "tsh2", userId: "tu2", fromStatus: "new", toStatus: "shortlisted", remarks: "Impressive profile", createdAt: new Date("2026-07-03T11:00:00Z") }] } }, interviews: { create: { id: "tiv1", tenantId: TENANT_ID, type: "video", date: "2026-07-20", time: "11:00", meetLink: "https://meet.google.com/lhc-card-001", panelMembers: ["Dr. Arjun Mehta", "Dr. Fatima Sheikh"], notes: "Technical assessment", status: "scheduled", reminderSent: true } } } });

  await prisma.candidate.create({ data: { id: "tc2", tenantId: TENANT_ID, applicationNumber: "LHC-2026-002", fullName: "Ms. Reema Patil", gender: "female", dob: "1993-06-20", email: "reema.patil@email.com", mobile: "+91 98765 20002", whatsapp: "+91 98765 20002", whatsappVerified: true, emailVerified: true, address: "34 Juhu Tara Road", city: "Mumbai", state: "Maharashtra", pin: "400049", qualification: "B.Sc Nursing", experience: "4 years", currentEmployer: "Hinduja Hospital", currentSalary: 45000, expectedSalary: 65000, noticePeriod: "30 days", languages: ["English", "Hindi", "Marathi"], skills: ["Critical Care", "Ventilator Management"], jobId: "tj2", applicationDate: new Date("2026-07-05"), status: "interview_scheduled", assignedHRId: "tu4", tags: ["icu_specialist"], score: { create: { communication: 7, technicalSkill: 8, experience: 6, qualification: 7, personality: 8, hospitalCultureFit: 7, computerKnowledge: 5, leadership: 6, confidence: 7, overall: 6.9 } }, communications: { createMany: { data: [{ id: "tcm2", type: "whatsapp", direction: "outbound", content: "Hi Reema, your application for ICU Nurse has been received.", status: "delivered", createdAt: new Date("2026-07-05T10:00:00Z") }] } }, statusHistory: { createMany: { data: [{ id: "tsh3", userId: "tu4", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-05T08:00:00Z") }, { id: "tsh4", userId: "tu4", fromStatus: "new", toStatus: "interview_scheduled", remarks: "Quick shortlist", createdAt: new Date("2026-07-06T10:00:00Z") }] } }, interviews: { create: { id: "tiv2", tenantId: TENANT_ID, type: "offline", date: "2026-07-18", time: "14:00", location: "Lords Health Care - Bandra", panelMembers: ["Ms. Neelam Joshi", "Dr. Shweta Patel"], notes: "Practical nursing assessment", status: "scheduled", reminderSent: false } } } });

  await prisma.candidate.create({ data: { id: "tc3", tenantId: TENANT_ID, applicationNumber: "LHC-2026-003", fullName: "Dr. Sanjay Gupta", gender: "male", dob: "1980-11-02", email: "sanjay.gupta@email.com", mobile: "+91 98765 20003", whatsapp: "+91 98765 20003", whatsappVerified: true, emailVerified: true, address: "56 Model Colony", city: "Pune", state: "Maharashtra", pin: "411016", qualification: "DM Neurology", experience: "12 years", currentEmployer: "Deenanath Mangeshkar Hospital", currentSalary: 320000, expectedSalary: 450000, noticePeriod: "90 days", languages: ["English", "Hindi", "Marathi"], skills: ["Stroke Management", "EEG", "EMG"], jobId: "tj3", applicationDate: new Date("2026-07-03"), status: "under_review", assignedHRId: "tu2", tags: ["senior", "experienced"], score: { create: { communication: 8, technicalSkill: 9, experience: 9, qualification: 9, personality: 7, hospitalCultureFit: 7, computerKnowledge: 6, leadership: 7, confidence: 8, overall: 7.9 } }, statusHistory: { createMany: { data: [{ id: "tsh5", userId: "tu2", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-03T08:00:00Z") }, { id: "tsh6", userId: "tu2", fromStatus: "new", toStatus: "under_review", remarks: "Reviewing profile", createdAt: new Date("2026-07-05T09:00:00Z") }] } } } });

  await prisma.candidate.create({ data: { id: "tc4", tenantId: TENANT_ID, applicationNumber: "LHC-2026-004", fullName: "Mr. Harsh Mehta", gender: "male", dob: "1987-09-18", email: "harsh.mehta@email.com", mobile: "+91 98765 20004", whatsapp: "+91 98765 20004", whatsappVerified: true, emailVerified: true, address: "89 Viman Nagar", city: "Pune", state: "Maharashtra", pin: "411014", qualification: "MS Orthopedics", experience: "9 years", currentEmployer: "Sancheti Hospital", currentSalary: 250000, expectedSalary: 400000, noticePeriod: "60 days", languages: ["English", "Hindi", "Marathi"], skills: ["Joint Replacement", "Arthroscopy"], jobId: "tj4", applicationDate: new Date("2026-07-02"), status: "interview_completed", assignedHRId: "tu3", tags: ["experienced"], score: { create: { communication: 7, technicalSkill: 8, experience: 8, qualification: 8, personality: 8, hospitalCultureFit: 7, computerKnowledge: 6, leadership: 7, confidence: 8, overall: 7.6 } }, interviews: { create: { id: "tiv3", tenantId: TENANT_ID, type: "offline", date: "2026-07-12", time: "10:00", location: "Lords Health Care - Thane", panelMembers: ["Dr. Vikram Joshi", "Mr. Rohan Desai"], notes: "Surgical skills assessment", status: "completed", rating: 8, feedback: "Excellent surgical skills" } }, statusHistory: { createMany: { data: [{ id: "tsh7", userId: "tu3", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-02T08:00:00Z") }, { id: "tsh8", userId: "tu3", fromStatus: "new", toStatus: "shortlisted", createdAt: new Date("2026-07-03T10:00:00Z") }, { id: "tsh9", userId: "tu3", fromStatus: "shortlisted", toStatus: "interview_scheduled", createdAt: new Date("2026-07-05T09:00:00Z") }, { id: "tsh10", userId: "tu3", fromStatus: "interview_scheduled", toStatus: "interview_completed", remarks: "Interview done", createdAt: new Date("2026-07-12T12:00:00Z") }] } } } });

  await prisma.candidate.create({ data: { id: "tc5", tenantId: TENANT_ID, applicationNumber: "LHC-2026-005", fullName: "Dr. Neha Deshmukh", gender: "female", dob: "1990-04-28", email: "neha.deshmukh@email.com", mobile: "+91 98765 20005", whatsapp: "+91 98765 20005", whatsappVerified: true, emailVerified: true, address: "23 FC Road", city: "Mumbai", state: "Maharashtra", pin: "400034", qualification: "MD Radiology", experience: "6 years", currentEmployer: "KEM Hospital", currentSalary: 180000, expectedSalary: 280000, noticePeriod: "30 days", languages: ["English", "Hindi", "Marathi"], skills: ["MRI", "CT Scan", "Mammography"], jobId: "tj5", applicationDate: new Date("2026-07-07"), status: "new", score: { create: { communication: 7, technicalSkill: 7, experience: 6, qualification: 7, personality: 7, hospitalCultureFit: 6, computerKnowledge: 7, leadership: 5, confidence: 6, overall: 6.5 } }, statusHistory: { create: { id: "tsh11", userId: "tu2", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-07T08:00:00Z") } } } });

  await prisma.candidate.create({ data: { id: "tc6", tenantId: TENANT_ID, applicationNumber: "LHC-2026-006", fullName: "Dr. Karan Joshi", gender: "male", dob: "1983-08-12", email: "karan.joshi@email.com", mobile: "+91 98765 20006", whatsapp: "+91 98765 20006", whatsappVerified: true, emailVerified: true, address: "78 Shankar Nagar", city: "Nagpur", state: "Maharashtra", pin: "440010", qualification: "MD Emergency Medicine", experience: "8 years", currentEmployer: "Alexis Multispeciality", currentSalary: 190000, expectedSalary: 300000, noticePeriod: "45 days", languages: ["English", "Hindi", "Marathi"], skills: ["Trauma Care", "ACLS", "ATLS"], jobId: "tj6", applicationDate: new Date("2026-06-28"), status: "offer_sent", assignedHRId: "tu8", tags: ["top_candidate"], score: { create: { communication: 8, technicalSkill: 8, experience: 8, qualification: 8, personality: 8, hospitalCultureFit: 9, computerKnowledge: 7, leadership: 8, confidence: 8, overall: 8.1 } }, remarks: { create: { id: "tr2", userId: "tu8", type: "overall", content: "Strong emergency physician. Quick decision maker.", isPinned: true, colorLabel: "green" } }, communications: { createMany: { data: [{ id: "tcm3", type: "whatsapp", direction: "outbound", content: "Dear Karan, we are pleased to inform you that you have been selected.", status: "delivered", createdAt: new Date("2026-07-10T10:00:00Z") }] } }, interviews: { create: { id: "tiv4", tenantId: TENANT_ID, type: "video", date: "2026-07-10", time: "15:00", meetLink: "https://meet.google.com/lhc-em-001", panelMembers: ["Dr. Shweta Patel", "Soyeb Alam"], notes: "Final interview", status: "completed", rating: 8, feedback: "Excellent fit for our team" } }, statusHistory: { createMany: { data: [{ id: "tsh12", userId: "tu8", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-06-28T08:00:00Z") }, { id: "tsh13", userId: "tu8", fromStatus: "new", toStatus: "shortlisted", createdAt: new Date("2026-06-30T10:00:00Z") }, { id: "tsh14", userId: "tu8", fromStatus: "shortlisted", toStatus: "interview_scheduled", createdAt: new Date("2026-07-02T09:00:00Z") }, { id: "tsh15", userId: "tu8", fromStatus: "interview_scheduled", toStatus: "interview_completed", createdAt: new Date("2026-07-10T16:00:00Z") }, { id: "tsh16", userId: "tu8", fromStatus: "interview_completed", toStatus: "offer_sent", remarks: "Offer extended", createdAt: new Date("2026-07-11T14:00:00Z") }] } } } });

  await prisma.candidate.create({ data: { id: "tc7", tenantId: TENANT_ID, applicationNumber: "LHC-2026-007", fullName: "Mr. Ravi Shinde", gender: "male", dob: "1994-12-05", email: "ravi.shinde@email.com", mobile: "+91 98765 20007", whatsapp: "+91 98765 20007", whatsappVerified: false, emailVerified: true, address: "45 MG Road", city: "Nashik", state: "Maharashtra", pin: "422001", qualification: "Pharm.D", experience: "4 years", currentEmployer: "Cipla Hospital", currentSalary: 42000, expectedSalary: 65000, noticePeriod: "15 days", languages: ["English", "Hindi", "Marathi"], skills: ["Clinical Pharmacy", "Drug Interaction"], jobId: "tj7", applicationDate: new Date("2026-07-09"), status: "new", score: { create: { communication: 6, technicalSkill: 6, experience: 5, qualification: 7, personality: 7, hospitalCultureFit: 6, computerKnowledge: 5, leadership: 4, confidence: 5, overall: 5.7 } }, statusHistory: { create: { id: "tsh17", userId: "tu9", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-09T08:00:00Z") } } } });

  await prisma.candidate.create({ data: { id: "tc8", tenantId: TENANT_ID, applicationNumber: "LHC-2026-008", fullName: "Ms. Pallavi Kulkarni", gender: "female", dob: "1995-01-30", email: "pallavi.kulkarni@email.com", mobile: "+91 98765 20008", whatsapp: "+91 98765 20008", whatsappVerified: true, emailVerified: true, address: "12 Shahu Colony", city: "Aurangabad", state: "Maharashtra", pin: "431001", qualification: "B.Sc MLT", experience: "2 years", currentEmployer: "Metropolis Lab", currentSalary: 25000, expectedSalary: 38000, noticePeriod: "Immediate", languages: ["English", "Hindi", "Marathi"], skills: ["Hematology", "Biochemistry"], jobId: "tj8", applicationDate: new Date("2026-07-12"), status: "under_review", assignedHRId: "tu3", tags: ["entry_level"], score: { create: { communication: 6, technicalSkill: 6, experience: 4, qualification: 5, personality: 7, hospitalCultureFit: 7, computerKnowledge: 6, leadership: 3, confidence: 6, overall: 5.6 } }, statusHistory: { createMany: { data: [{ id: "tsh18", userId: "tu3", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-12T08:00:00Z") }, { id: "tsh19", userId: "tu3", fromStatus: "new", toStatus: "under_review", remarks: "Reviewing", createdAt: new Date("2026-07-13T10:00:00Z") }] } } } });

  await prisma.candidate.create({ data: { id: "tc9", tenantId: TENANT_ID, applicationNumber: "LHC-2026-009", fullName: "Dr. Mohan Patil", gender: "male", dob: "1986-07-22", email: "mohan.patil@email.com", mobile: "+91 98765 20009", whatsapp: "+91 98765 20009", whatsappVerified: true, emailVerified: true, address: "90 Tarabai Park", city: "Kolhapur", state: "Maharashtra", pin: "416003", qualification: "MD Pediatrics", experience: "7 years", currentEmployer: "Chittaranjan Hospital", currentSalary: 140000, expectedSalary: 250000, noticePeriod: "30 days", languages: ["English", "Hindi", "Marathi", "Kannada"], skills: ["Neonatology", "Pediatric Care"], jobId: "tj9", applicationDate: new Date("2026-07-04"), status: "selected", assignedHRId: "tu2", tags: ["experienced"], score: { create: { communication: 7, technicalSkill: 7, experience: 7, qualification: 8, personality: 8, hospitalCultureFit: 8, computerKnowledge: 6, leadership: 6, confidence: 7, overall: 7.1 } }, statusHistory: { createMany: { data: [{ id: "tsh20", userId: "tu2", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-04T08:00:00Z") }, { id: "tsh21", userId: "tu2", fromStatus: "new", toStatus: "selected", remarks: "Direct selection - excellent profile", createdAt: new Date("2026-07-08T16:00:00Z") }] } } } });

  await prisma.candidate.create({ data: { id: "tc10", tenantId: TENANT_ID, applicationNumber: "LHC-2026-010", fullName: "Mr. Anand Tiwari", gender: "male", dob: "1982-03-14", email: "anand.tiwari@email.com", mobile: "+91 98765 20010", whatsapp: "+91 98765 20010", whatsappVerified: true, emailVerified: true, address: "45 Palm Beach Road", city: "Navi Mumbai", state: "Maharashtra", pin: "400703", qualification: "MHA", experience: "11 years", currentEmployer: "Wockhardt Hospitals", currentSalary: 130000, expectedSalary: 200000, noticePeriod: "60 days", languages: ["English", "Hindi", "Marathi"], skills: ["Operations", "Compliance", "Budgeting"], jobId: "tj10", applicationDate: new Date("2026-07-06"), status: "interview_scheduled", assignedHRId: "tu5", tags: ["senior"], score: { create: { communication: 8, technicalSkill: 7, experience: 9, qualification: 7, personality: 8, hospitalCultureFit: 8, computerKnowledge: 7, leadership: 8, confidence: 8, overall: 7.9 } }, interviews: { create: { id: "tiv5", tenantId: TENANT_ID, type: "offline", date: "2026-07-25", time: "10:00", location: "Lords Health Care - Navi Mumbai", panelMembers: ["Soyeb Alam", "Dr. Fatima Sheikh"], notes: "Operations round", status: "scheduled", reminderSent: true } }, statusHistory: { createMany: { data: [{ id: "tsh22", userId: "tu5", fromStatus: null, toStatus: "new", remarks: "Application submitted", createdAt: new Date("2026-07-06T08:00:00Z") }, { id: "tsh23", userId: "tu5", fromStatus: "new", toStatus: "interview_scheduled", remarks: "Fast-tracked", createdAt: new Date("2026-07-07T10:00:00Z") }] } } } });

  console.log("10 Candidates created.");

  // 10 Notifications
  await prisma.notification.createMany({ data: [
    { id: "tn1", tenantId: TENANT_ID, type: "application", title: "New Application", message: "Dr. Aisha Khan applied for Senior Cardiologist", read: false, candidateId: "tc1" },
    { id: "tn2", tenantId: TENANT_ID, type: "application", title: "New Application", message: "Ms. Reema Patil applied for ICU Nurse", read: false, candidateId: "tc2" },
    { id: "tn3", tenantId: TENANT_ID, type: "interview", title: "Interview Tomorrow", message: "Interview with Dr. Karan Joshi tomorrow at 3:00 PM", read: false, candidateId: "tc6" },
    { id: "tn4", tenantId: TENANT_ID, type: "status_change", title: "Candidate Shortlisted", message: "Dr. Sanjay Gupta moved to Under Review", read: false, candidateId: "tc3" },
    { id: "tn5", tenantId: TENANT_ID, type: "status_change", title: "Offer Sent", message: "Offer sent to Dr. Karan Joshi", read: true, candidateId: "tc6" },
    { id: "tn6", tenantId: TENANT_ID, type: "reminder", title: "Follow Up Required", message: "Follow up with Aisha Khan regarding interview feedback", read: false, candidateId: "tc1" },
    { id: "tn7", tenantId: TENANT_ID, type: "interview", title: "Interview Feedback Pending", message: "Please submit feedback for Harsh Mehta interview", read: false, candidateId: "tc4" },
    { id: "tn8", tenantId: TENANT_ID, type: "application", title: "New Application", message: "Ms. Pallavi Kulkarni applied for Lab Technician", read: true, candidateId: "tc8" },
    { id: "tn9", tenantId: TENANT_ID, type: "status_change", title: "Candidate Selected", message: "Dr. Mohan Patil has been selected for Pediatrics", read: true, candidateId: "tc9" },
    { id: "tn10", tenantId: TENANT_ID, type: "reminder", title: "Upcoming Interview", message: "Interview with Anand Tiwari on July 25th", read: false, candidateId: "tc10" },
  ]});
  console.log("10 Notifications created.");

  // 10 Templates
  await prisma.template.createMany({ data: [
    { id: "tt1", tenantId: TENANT_ID, name: "Application Confirmation", type: "whatsapp", content: "Dear {{name}}, thank you for applying for {{position}} at Lords Health Care. We will review your application shortly.", variables: ["name", "position"] },
    { id: "tt2", tenantId: TENANT_ID, name: "Interview Invitation", type: "whatsapp", content: "Hi {{name}}, you have been shortlisted for {{position}}. Please join us on {{date}} at {{time}} at {{location}}.", variables: ["name", "position", "date", "time", "location"] },
    { id: "tt3", tenantId: TENANT_ID, name: "Document Reminder", type: "whatsapp", content: "Dear {{name}}, please submit the following documents: {{documents}}.", variables: ["name", "documents"] },
    { id: "tt4", tenantId: TENANT_ID, name: "Offer Letter", type: "email", subject: "Offer of Employment - {{position}} at Lords Health Care", content: "Dear {{name}},\n\nCongratulations! We are pleased to offer you the position of {{position}} at Lords Health Care.\n\nPlease find attached the offer letter.\n\nBest regards,\nHR Team\nLords Health Care", variables: ["name", "position"] },
    { id: "tt5", tenantId: TENANT_ID, name: "Rejection Notice", type: "email", subject: "Application Status - {{position}}", content: "Dear {{name}},\n\nThank you for your interest in {{position}} at Lords Health Care. After careful review, we have decided to move forward with other candidates.\n\nBest regards,\nHR Team\nLords Health Care", variables: ["name", "position"] },
    { id: "tt6", tenantId: TENANT_ID, name: "Interview Reminder", type: "whatsapp", content: "Reminder: You have an interview for {{position}} tomorrow at {{time}}. Please be at {{location}} 15 minutes early.", variables: ["position", "time", "location"] },
    { id: "tt7", tenantId: TENANT_ID, name: "Offer Acceptance", type: "whatsapp", content: "Dear {{name}}, we are delighted to welcome you to Lords Health Care! Please report on {{date}} at {{time}} to the HR department.", variables: ["name", "date", "time"] },
    { id: "tt8", tenantId: TENANT_ID, name: "Screening Questions", type: "whatsapp", content: "Hi {{name}}, please answer a few screening questions for {{position}}: 1. {{q1}} 2. {{q2}}", variables: ["name", "position", "q1", "q2"] },
    { id: "tt9", tenantId: TENANT_ID, name: "Background Check Request", type: "email", subject: "Background Check Authorization - {{position}}", content: "Dear {{name}},\n\nAs part of our hiring process for {{position}}, please complete the background check authorization form attached.\n\nRegards,\nHR Team", variables: ["name", "position"] },
    { id: "tt10", tenantId: TENANT_ID, name: "Welcome Onboarding", type: "email", subject: "Welcome to Lords Health Care!", content: "Dear {{name}},\n\nWelcome to the team! Your onboarding is scheduled for {{date}}.\n\nPlease bring the following:\n1. Photo ID\n2. Degree certificates\n3. Previous employment letters\n\nBest,\nHR Team", variables: ["name", "date"] },
  ]});
  console.log("10 Templates created.");

  // 10 Audit Logs
  await prisma.auditLog.createMany({ data: [
    { id: "ta1", tenantId: TENANT_ID, userId: "tu2", action: "Application Received", entity: "Candidate", entityId: "tc1", details: "Aisha Khan applied for Senior Cardiologist", createdAt: new Date("2026-07-01T08:00:00Z") },
    { id: "ta2", tenantId: TENANT_ID, userId: "tu4", action: "Interview Scheduled", entity: "Candidate", entityId: "tc2", details: "Reema Patil interview scheduled at Bandra branch", createdAt: new Date("2026-07-06T10:30:00Z") },
    { id: "ta3", tenantId: TENANT_ID, userId: "tu8", action: "Offer Sent", entity: "Candidate", entityId: "tc6", details: "Offer sent to Karan Joshi for Emergency Physician", createdAt: new Date("2026-07-11T14:00:00Z") },
    { id: "ta4", tenantId: TENANT_ID, userId: "tu2", action: "Candidate Selected", entity: "Candidate", entityId: "tc9", details: "Mohan Patil directly selected for Pediatrics", createdAt: new Date("2026-07-08T16:00:00Z") },
    { id: "ta5", tenantId: TENANT_ID, userId: "tu3", action: "Application Reviewed", entity: "Candidate", entityId: "tc8", details: "Pallavi Kulkarni moved to Under Review", createdAt: new Date("2026-07-13T10:00:00Z") },
    { id: "ta6", tenantId: TENANT_ID, userId: "tu1", action: "Job Created", entity: "Vacancy", entityId: "tj1", details: "Created Senior Cardiologist position", createdAt: new Date("2026-06-15T09:00:00Z") },
    { id: "ta7", tenantId: TENANT_ID, userId: "tu1", action: "Job Created", entity: "Vacancy", entityId: "tj2", details: "Created ICU Nurse position", createdAt: new Date("2026-06-16T10:00:00Z") },
    { id: "ta8", tenantId: TENANT_ID, userId: "tu2", action: "Remark Added", entity: "Candidate", entityId: "tc1", details: "Added overall remark for Aisha Khan", createdAt: new Date("2026-07-03T11:30:00Z") },
    { id: "ta9", tenantId: TENANT_ID, userId: "tu1", action: "Login", entity: "User", entityId: "tu1", details: "Soyeb Alam logged in", createdAt: new Date("2026-07-17T08:30:00Z") },
    { id: "ta10", tenantId: TENANT_ID, userId: "tu3", action: "Interview Completed", entity: "Candidate", entityId: "tc4", details: "Harsh Mehta interview completed with rating 8/10", createdAt: new Date("2026-07-12T12:00:00Z") },
  ]});
  console.log("10 Audit Logs created.");

  console.log("Seed completed for Lords Health Care!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
